config/routes.rb
Nucore::Application.routes.draw do
  match '/users/sign_in.pdf' => redirect('/users/sign_in')
  devise_for :users, :skip => :passwords

  if SettingsHelper.feature_on?(:password_update)
    match '/users/password/edit_current', :to => 'user_password#edit_current', :as => 'edit_current_password'
    match '/users/password/reset',        :to => 'user_password#reset',        :as => 'reset_password'
    match '/users/password/edit',         :to => 'user_password#edit',         :as => 'edit_password'
    match '/users/password/update',       :to => 'user_password#update',       :as => 'update_password'
  end

  # root route
  root :to => 'public#index'

  # authentication
  match 'switch_back',   :to => 'public#switch_back'

  # shared searches
  post  '/user_search_results', :to => 'search#user_search_results'
  match '/facilities/:facility_id/price_group/:price_group_id/account_price_group_members/search_results', :to => 'account_price_group_members#search_results'
  match '/facilities/:facility_id/accounts/user/:user_id', :to => 'facility_accounts#user_accounts', :as => 'user_accounts'

  post  'order_search' => 'order_search#index', :as => 'order_search'

  # front-end accounts
  resources :accounts, :only => [:index, :show] do
    member do
      get 'user_search'
      get 'transactions'
      get 'transactions_in_review'
    end

    if SettingsHelper.feature_on? :suspend_accounts
      match 'suspend', :to => 'accounts#suspend', :as => 'suspend'
      match 'unsuspend', :to => 'accounts#unsuspend', :as => 'unsuspend'
    end

    resources :account_users, :only => [:new, :destroy, :create, :index] do
      collection do
        get 'user_search'
      end
    end

    resources :statements, :only => [:index]

    resources :facilities, :only => [] do
      resources :statements, :only => [:show]
    end
  end

  # transaction searches
  match '/transactions', :to => 'transaction_history#my_history', :as => 'transaction_history'

  # global settings
  resources :affiliates, :except => :show

  resources :facilities, :except => [:delete] do
    collection do
      get 'list'
    end

    member do
      get 'manage'
    end

    resources :products, :only => [:index] do
      resources :product_accessories, :only => [:index, :create, :destroy], :path => 'accessories'
    end

    match 'instrument_statuses', :to => 'instruments#instrument_statuses', :as => 'instrument_statuses'

    resources :instruments do
      member do
        get 'manage'
      end

      match 'public_schedule', :to => 'instruments#public_schedule'
      match 'schedule',        :to => 'instruments#schedule'
      match 'agenda',          :to => 'instruments#agenda'
      match 'status',          :to => 'instruments#instrument_status'
      match 'switch',          :to => 'instruments#switch'

      resources :schedule_rules, :except => [:show]
      resources :product_access_groups
      resources :price_policies, :controller => 'instrument_price_policies', :except => [:show]
      resources :reservations, :only => [:new, :create, :destroy], :controller => 'facility_reservations' do
        get 'edit_admin',   :to => 'facility_reservations#edit_admin'
        put 'update_admin', :to => 'facility_reservations#update_admin'
      end

      resources :reservations, :only => [:index]
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to => 'product_users#user_search_results'
      match 'update_restrictions',        :to => 'product_users#update_restrictions'
    end

    resources :services do
      member do
        get 'manage'
      end
      resources :price_policies, :controller => 'service_price_policies', :except => [:show]
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to =>'product_users#user_search_results'
    end

    resources :items do
      member do
        get 'manage'
      end
      resources :price_policies, :controller => 'item_price_policies', :except => [:show]
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to =>'product_users#user_search_results'
    end

    resources :bundles do
      member do
        get 'manage'
      end
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to =>'product_users#user_search_results'
      resources :bundle_products, :controller => 'bundle_products', :except => [:show]
    end

    resources :price_group_products, :only => [:edit, :update]

    match 'schedule', :to => 'facilities#schedule'
    match 'agenda',   :to => 'facilities#agenda'
    resources :order_statuses, :except => [:show]

    resources :facility_users, :controller => 'facility_users', :only => [:index, :destroy] do
      collection do
        get 'search'
      end
      match 'map_user', :to => 'facility_users#map_user'
    end

    ### Feature Toggle Create Users ###
    if SettingsHelper.feature_on?(:create_users)
      resources :users, :except => [:edit, :update] do
        collection do
          get 'new_external'
          post 'search'
        end
        get   'switch_to',    :to => 'users#switch_to'
        match 'orders',       :to => 'users#orders'
        match 'reservations', :to => 'users#reservations'
        match 'accounts',     :to => 'users#accounts'
        match 'instruments',  :to => 'users#instruments'
      end
    else
      resources :users, :except => [:edit, :update, :new, :create], :constraints => {:id => /\d+/} do
        get   'switch_to',    :to => 'users#switch_to'
        match 'orders',       :to => 'users#orders'
        match 'reservations', :to => 'users#reservations'
        match 'accounts',     :to => 'users#accounts'
        match 'instruments',  :to => 'users#instruments'
      end
    end
    ######

    resources :facility_accounts, :controller => 'facility_facility_accounts', :only => [:index, :new, :create, :edit, :update] if SettingsHelper.feature_on? :recharge_accounts

    resources :orders, :controller => 'facility_orders', :only => [:index, :edit, :update, :show] do
      member do
        post 'send_receipt'
      end

      collection do
        post 'batch_update'
        get 'show_problems'
        get 'disputed'
        get 'tab_counts'
      end

      resources :order_details, :controller => 'facility_order_details', :only => [:edit, :update, :destroy] do
        member do
          get 'remove_from_journal'
        end
        get 'new_price', :to => 'facility_order_details#new_price'
        put 'resolve_dispute', :to => 'facility_order_details#resolve_dispute'
        resources :reservations, :controller => 'facility_reservations', :only => [:edit, :update, :show]
        get 'manage', :to => 'order_management/order_details#edit', :on => :member
        put 'manage', :to => 'order_management/order_details#update', :on => :member
        get 'pricing', :to => 'order_management/order_details#pricing', :on => :member
        get 'files', :to => 'order_management/order_details#files', :on => :member
      end
    end

    resources :order_imports, :only => [ :new, :create ]

    resources :reservations, :controller => 'facility_reservations', :only => :index do
      collection do
        post 'batch_update'
        get 'show_problems'
        get 'disputed'
        get 'timeline'
        get 'tab_counts'
      end
    end

    get 'accounts_receivable', :to => 'facility_accounts#accounts_receivable'

    ### Feature Toggle Editing Accounts ###
    if SettingsHelper.feature_on?(:edit_accounts)
      resources :accounts, :controller => 'facility_accounts', :only => [:new, :create, :edit, :update] do
        collection do
          get 'new_account_user_search'
          get 'user_search'
        end
        resources :account_users, :controller => 'facility_account_users', :only => [:new, :destroy, :create, :update] do
          collection do
            get 'user_search'
          end
        end
      end
    end

    resources :accounts, :controller => 'facility_accounts', :only => [:index, :show] do
      collection do
        get 'search'
        match 'search_results', :via => [:get, :post]
      end
      get '/members',                          :to => 'facility_accounts#members',        :as => 'members'
      get '/statements/:statement_id(.:format)', :to => 'facility_accounts#show_statement', :as => 'statement', :defaults => { :format => 'html' } if AccountManager.using_statements?

      if SettingsHelper.feature_on?(:suspend_accounts)
        match 'suspend',   :to => 'facility_accounts#suspend',   :as => 'suspend'
        match 'unsuspend', :to => 'facility_accounts#unsuspend', :as => 'unsuspend'
      end
    end

    ######

    resources :journals, :controller => 'facility_journals', :only => [:index, :new, :create, :update, :show] do
      post 'reconcile', :to => 'facility_journals#reconcile'
    end

    get 'bulk_email', :to => 'bulk_email#search'

    resources :price_groups do
      member do
        get 'users'
        get 'accounts'
      end

      resources :user_price_group_members, :only => [:new, :destroy, :create]

      resources :account_price_group_members, :only => [:new, :destroy, :create]
    end

    get 'notifications',       :to => 'facility_notifications#index'
    post 'notifications/send', :to => 'facility_notifications#send_notifications', :as => 'send_notifications'
    get 'transactions',        :to => 'facilities#transactions'
    get 'in_review',           :to => 'facility_notifications#in_review',          :as => 'notifications_in_review'
    post 'in_review/mark',     :to => 'facility_notifications#mark_as_reviewed',   :as => 'notifications_mark_as_reviewed'

    resources :statements, :controller => 'facility_statements', :only => [:index, :new, :show] do

app/models/user.rb
class User < ActiveRecord::Base

  module Overridable
    def price_groups
      groups = price_group_members.collect{ |pgm| pgm.price_group }
      # check internal/external membership
      groups << (self.username.match(/@/) ? PriceGroup.external.first : PriceGroup.base.first)
      groups.flatten.uniq
    end
  end

  include Overridable
  include Role

  # ldap_authenticatable is included via a to_prepare hook if ldap is enabled
  devise :database_authenticatable, :encryptable, :trackable, :recoverable

  has_many :accounts, :through => :account_users
  has_many :account_users, :conditions => {:deleted_at => nil}
  has_many :orders
  has_many :order_details, :through => :orders
  has_many :price_group_members
  has_many :product_users
  has_many :notifications
  has_many :products, :through => :product_users
  has_many :assigned_order_details, :class_name => 'OrderDetail', :foreign_key => 'assigned_user_id'
  has_many :user_roles, :dependent => :destroy
  has_many :facilities, :through => :user_roles

  validates_presence_of :username, :first_name, :last_name
  validates_format_of :email, :with => /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,6}$/i
  validates_uniqueness_of :username, :email

  #
  # Gem ldap_authenticatable expects User to respond_to? :login. For us that's #username.
  alias_attribute :login, :username

  #
  # Gem ldap_authenticatable expects User to respond_to? :ldap_attributes. For us should return nil.
  attr_accessor :ldap_attributes


  # Scopes
  def self.with_recent_orders(facility)
    order_query = Order.recent.for_facility(facility)
    select("DISTINCT users.*")
      .joins(:orders)
      .merge(order_query)
  end


  # finds all user role mappings for a this user in a facility
  def facility_user_roles(facility)
    UserRole.find_all_by_facility_id_and_user_id(facility.id, id)
  end

  #
  # Returns true if the user is authenticated against nucore's
  # user table, false if authenticated by an external system
  def authenticated_locally?
    encrypted_password.present? && password_salt.present?
  end

  #
  # Returns true if this user is external to organization, false othewise
  def external?
    username.downcase == email.downcase
  end

  def password_updatable?
    external?
  end

  def update_password_confirm_current(params)
    unless self.valid_password? params[:current_password]
      self.errors.add(:current_password, :incorrect)
    end
    update_password(params)
  end
  def update_password(params)
    unless password_updatable?
      self.errors.add(:base, :password_not_updatable)
      return false
    end

    self.errors.add(:password, :empty) if params[:password].blank?
    self.errors.add(:password, :password_too_short) if params[:password] and params[:password].strip.length < 6
    self.errors.add(:password_confirmation, :confirmation) if params[:password] != params[:password_confirmation]

    if self.errors.empty?
      self.password = params[:password].strip
      self.clear_reset_password_token
      self.save!
      return true
    else
      return false
    end


  end
  # Find the users for a facility
  # TODO: move this to facility?
  def self.find_users_by_facility(facility)
    find_by_sql(<<-SQL)
      SELECT u.*
      FROM #{User.table_name} u
      LEFT JOIN #{UserRole.table_name} ur ON u.id=ur.user_id
      WHERE ur.facility_id = #{facility.id}
      ORDER BY LOWER(ur.role), LOWER(u.last_name), LOWER(u.first_name)
    SQL
  end

  #
  # A cart is an order. This method finds this user's order.
  # [_created_by_user_]
  #   The user that created the order we want. +self+ is
  #   inferred if left nil.
  # [_find_existing_]
  #   true if we want to look in the DB for an order to add
  #   new +OrderDetail+s to, false if we want a brand new order
  def cart(created_by_user = nil, find_existing=true)
    if find_existing
      Cart.new(self, created_by_user).order
    else
      Cart.new(self, created_by_user).new_cart
    end
  end

  def account_price_groups
    groups = self.accounts.active.collect{ |a| a.price_groups }.flatten.uniq
  end


  #
  # Given a +Product+ returns all valid accounts this user has for
  # purchasing that product
  def accounts_for_product(product)
    acts=accounts.active.for_facility(product.facility)
    acts.reject!{|acct| !acct.validate_against_product(product, self).nil?}
    acts
  end


  def full_name
    unless first_name.nil? and last_name.nil?
      full = ""
      full += first_name unless first_name.nil?
      full += " " unless first_name.nil? || last_name.nil?
      full += last_name unless last_name.nil?
      full
    else
      username
    end
  end

  def to_s
    full_name
  end
end

app/helpers/facility_orders_helper.rb
module FacilityOrdersHelper
  def order_detail_notices(order_detail)
    notices = []

    notices << 'in_review' if order_detail.in_review?
    # notices << 'reviewed' if order_detail.reviewed?
    notices << 'in_dispute' if order_detail.in_dispute?
    notices << 'can_reconcile' if order_detail.can_reconcile?
    notices << 'in_open_journal' if order_detail.in_open_journal?

    warnings = []
    warnings << 'missing_actuals' if order_detail.complete? && order_detail.reservation.try(:requires_but_missing_actuals?)
    warnings << 'missing_price_policy' if order_detail.missing_price_policy? && !order_detail.reservation.try(:requires_but_missing_actuals?)

    { :warnings => warnings, :notices => notices }
  end

  def order_detail_badges(order_detail)
    notices = order_detail_notices(order_detail)

    output = build_badges(notices[:warnings], 'label-important')
    output += build_badges(notices[:notices], 'label-info')

    output.join(' ').html_safe
  end

  def banner_date_label(object, field)
    banner_label(object, field) do |value|
      value = human_datetime value
      value = yield(value) if value && block_given?
      value
    end
  end

  def banner_label(object, field)
    if value = object.send(:try, field)
      value = yield(value) if block_given?

      content_tag :dl, :class => 'span2' do
        content_tag(:dt, object.class.human_attribute_name(field)) +
        content_tag(:dd, value)
      end
    end
  end

  private

  def build_badges(notices, label_class)
    notices.map do |notice|
      content_tag(:span, t("order_details.notices.#{notice}.badge"), :class => ['label', label_class])
    end
  end
end

app/views/facility_orders/_disputed_table.html.haml
%p.notice Please review the following disputes.
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Order
      %th Order Detail
      %th.med Order On
      %th.med Ordered By
      %th.med Ordered For
      %th.med Product
      %th.med Disputed On
      %th.auto Dispute Reason
  %tbody
    - @order_details.each do |od|
      - o = od.order
      - product_name = order_detail_description(od)
      %tr
        %td.centered= link_to od.order_id, facility_order_path(current_facility, od.order)
        %td.centered= link_to od.id, manage_order_detail_path(od), :class => 'manage-order-detail'
        %td=h human_datetime(o.ordered_at)
        %td=h User.find(o.created_by).full_name
        %td=h User.find(o.user_id).full_name
        %td= product_name
        %td=h human_datetime(od.dispute_at)
        %td=h od.dispute_reason
= will_paginate(@order_details)

app/views/facility_orders/_merge_order.html.haml
- if @merge_orders.present?
  .well
    %p.alert.alert-info= t 'facility_orders.edit.attention'
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th
          %th= t('orders.show.th.product')
          %th.centered= t('orders.show.th.quantity')
          %th.currency= t('orders.show.th.cost')
          - if @order.has_subsidies?
            %th.currency= t('orders.show.th.adjust')
          %th.currency= t('orders.show.th.extend')

      %tbody
        - @merge_orders.each do |order|
          - order.order_details.each do |detail|
            %tr
              %td.centered= link_to 'Remove', facility_order_order_detail_path(current_facility, order, detail), :method => :delete
              %td
                = render :partial => "orders/#{detail.product.class.name.downcase}_desc", :locals => { :order_detail => detail }
              %td.centered
                = detail.quantity
              - if detail.cost_estimated?
                %td.currency= show_estimated_cost(detail)
                - if @order.has_subsidies?
                  %td.currency= show_estimated_subsidy(detail)
                %td.currency= show_estimated_total(detail)
              - else
                %td.currency Unassigned
                - if @order.has_subsidies?
                  %td.currency Unassigned
                %td.currency Unassigned

app/views/facility_orders/_merge_order_form.html.haml
- if @merge_orders.blank?
  .well
    = form_for [current_facility, @order], :method => :put do |f|
      = text_field_tag :product_add_quantity, 1
      = select_tag :product_add, options_for_select(current_facility.products.active_plus_hidden.collect{|p| [ p.name, p.id ]})
      %br
      = submit_tag 'Add To Order', :class => 'btn btn-primary', :id => :product_add_btn

app/views/facility_orders/_order_file_icon.html.haml
- if od.survey_completed?
  .inline-icons
    = link_to od.external_service_receiver.response_data, :target => '_blank' do
      %i.icon-file-text{:data => { :toggle => 'tooltip' }, :title => t('order_details.show.link.view.order_form') }
- od.stored_files.template_result.each do |stored_file|
  .inline-icons
    = link_to stored_file.file.url do
      %i.icon-file-text{:data => { :toggle => 'tooltip' }, :title => t('order_details.show.link.view.order_file') }

app/views/facility_orders/_result_file_icon.html.haml
- if od.product.is_a?(Service)
  .inline-icons
    - result_file_count = od.stored_files.sample_result.count
    = link_to admin_order_detail_path(:files, od), :class => 'results-file-upload' do
      %i{:class => result_file_count > 0 ? 'icon-file' : 'icon-file-alt', :data => { :toggle => 'tooltip' }, :title => t('file_uploads.sample_result.count', :count => result_file_count) }

app/views/facility_orders/_send_receipt.html.haml
= form_for :order, :url => send_receipt_facility_order_path(current_facility, @order) do
  = submit_tag 'Send Receipt', :class => 'btn', :id => :send_receipt_btn

app/views/facility_orders/disputed.html.haml
= content_for :h1 do
  =h current_facility

= content_for :tabnav do
  = render :partial => 'admin/shared/tabnav_order', :locals => { :secondary_tab => 'disputed'}

- if @order_details.empty?
  %p.notice There are no "Disputed" orders.
- else
  = render :partial => 'facility_orders/disputed_table'

app/views/facility_orders/edit.html.haml
- content_for :head_content do
  = javascript_tag "$(function() { $('#product_add').chosen(); });"

- content_for(:h1) { t '.head.h1', :order_number => @order.id }
= render :partial => 'shared/order_details_table'

- if @merge_orders.blank?
  = form_for :order, :url => send_receipt_facility_order_path(current_facility, @order) do
    = hidden_field_tag :id, @order.id
    = submit_tag 'Send Receipt', :class => 'btn', :id => :send_receipt_btn
  = form_for :order, :url => facility_order_path(current_facility, @order), :html => { :method => :put } do
    = text_field_tag :product_add_quantity, 1
    = select_tag :product_add, options_for_select(current_facility.products.active_plus_hidden.collect{|p| [ p.name, p.id ]})
    %br
    = submit_tag 'Add To Order', :class => 'btn', :id => :product_add_btn

- else
  %div#merge-orders
    %p= t 'facility_orders.edit.attention'
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th
          %th= t('orders.show.th.product')
          %th.centered= t('orders.show.th.quantity')
          %th.currency= t('orders.show.th.cost')
          - if @order.has_subsidies?
            %th.currency= t('orders.show.th.adjust')
          %th.currency= t('orders.show.th.extend')

      %tbody
        - @merge_orders.each do |order|
          - order.order_details.each do |detail|
            %tr
              %td.centered= link_to 'Remove', facility_order_order_detail_path(current_facility, order, detail), :method => :delete
              %td
                = render :partial => "orders/#{detail.product.class.name.downcase}_desc", :locals => { :order_detail => detail }
              %td.centered
                = detail.quantity
              - if detail.cost_estimated?
                %td.currency= show_estimated_cost(detail)
                - if @order.has_subsidies?
                  %td.currency= show_estimated_subsidy(detail)
                %td.currency= show_estimated_total(detail)
              - else
                %td.currency Unassigned
                - if @order.has_subsidies?
                  %td.currency Unassigned
                %td.currency Unassigned

app/views/facility_orders/index.html.haml
= content_for :h1 do
  =h current_facility

= content_for :tabnav do
  = render :partial => 'admin/shared/tabnav_order', :locals => { :secondary_tab => 'new'}

- if @order_details.empty?
  %p.notice There are no "New" or "In Process" orders.
- else
  = form_tag(batch_update_facility_orders_path, :method => :post) do
    - facility_users = User.find_users_by_facility(current_facility)
    %table.table.table-striped.table-hover.old-table
      %thead
        %tr.borderless
          %td{ :colspan => 7 }= link_to 'Select All', 'JavaScript:void(0);', :class => 'select_all'
          = render :partial => 'shared/order_detail_action_form', :locals => { :button_label => 'Update Orders' }
        -## THE HEADER ROW
        %tr
          %th
          %th.order_num_width.centered= sortable 'order_number', 'Order'
          %th.order_num_width.centered= 'Order Detail'
          %th.ordered_on_width= sortable 'date', 'Ordered On'
          %th User Name
          %th{ :colspan => 2 }== Quantity / #{sortable 'product'}
          %th= sortable 'assigned_to'
          %th= sortable 'status'
          %th.currency Price

      -## THE DETAIL ROWS
      %tbody
        - @order_details.each do |od|
          - order = od.order
          %tr
            %td.centered= check_box_tag("order_detail_ids[]", od.id, false, {:class => 'toggle', :id => nil })
            %td.centered= link_to od.order_id, facility_order_path(current_facility, order)
            %td.centered= link_to od.id, manage_order_detail_path(od), :class => 'manage-order-detail'
            %td=h human_datetime(order.ordered_at)
            %td= order.user.full_name
            %td.centered= od.quantity
            = render :partial => 'shared/order_detail_cell', :locals => { :od => od }
            %td= od.assigned_user.nil? ? '' : od.assigned_user.full_name
            %td= od.order_status.name
            %td.currency
              - od.send(:extend, PriceDisplayment)
              = od.wrapped_total
        -## THE FOOTER CONTROL ROW
        %tr.borderless
          %td
          %td
          %td
          %td
          %td
          %td
          = render :partial => 'shared/order_detail_action_form', :locals => { :button_label => 'Update Orders' }
  = will_paginate(@order_details)
  = render :partial => '/price_display_footnote', :locals => { :admin => true }

app/views/facility_orders/show.html.haml
- content_for :h1 do
  = current_facility
%h2= "Order ##{@order.id}"

.container.banner-list
  .row
    = banner_date_label @order, :ordered_at
    = banner_label @order, :user
    = banner_label @order, :created_by_user
    - if @merge_orders.blank?
      .pull-right= render :partial => 'send_receipt'

= render :partial => 'merge_order'

%table.order-list.table.table-striped.table-hover#order-management
  %thead
    %tr
      %th{:colspan => 4}
      %th{:colspan => 2}= OrderDetail.human_attribute_name(:quantity)
      %th{:colspan => 3} Pricing
    %tr
      %th.order-id= OrderDetail.human_attribute_name(:id)
      %th.badges Status
      %th= Product.model_name.human
      %th
      %th.time Reserved
      %th.time Actual
      %th.currency Cost
      %th.currency Subsidy
      %th.currency Total
      %th.badges
  %tbody
    - @order_details.each do |od|
      - od.send(:extend, PriceDisplayment)
      %tr{:class => [od.parent_order_detail_id ? 'child' : 'parent', "status-#{od.order_status.root.name.underscore}", flash[:updated_order_details].try(:include?, od.id) ? 'updated-order-detail' : ''] }
        %td.order-id
          = link_to od, manage_order_detail_path(od), :class => 'manage-order-detail'
        %td.badges
          = status_badge(od)
        %td.product
          = od.product
          = "<br/>#{od.reservation}".html_safe if od.reservation
        %td.action
          - if od.add_accessories?
            = link_to new_order_order_detail_accessory_path(@order, od), :class => ['has_accessories', 'persistent'] do
              = tooltip_icon 'icon-plus-sign-alt', t('product_accessories.pick_accessories.title')
          = render :partial => 'order_file_icon', :locals => { :od => od }
          = render :partial => 'result_file_icon', :locals => { :od => od }

        %td.currency.timeinput= od.reservation.try(:duration_mins)
        - if od.reservation.try(:actual_duration_mins)
          %td.currency.timeinput= od.reservation.actual_duration_mins
        - elsif od.quantity_as_time?
          %td.currency.timeinput= od.quantity
        - else
          %td.currency= od.quantity
        %td.currency= od.wrapped_cost
        %td.currency= od.wrapped_subsidy
        %td.currency= od.wrapped_total
        %td.badges= order_detail_badges(od)

= render :partial => 'merge_order_form'

#order-detail-modal.modal.hide.fade{ :data => { :backdrop => 'static' } }

app/views/facility_orders/show_problems.html.haml
= content_for :h1 do
  =h current_facility

= content_for :tabnav do
  = render :partial => 'admin/shared/tabnav_order', :locals => { :secondary_tab => 'problem'}

- if @order_details.empty?
  %p.notice There are no problem orders.
- else
  %p.notice The order line items below are complete and either do not have a price policy or are instrument orders without usage information. Each will need to be corrected.
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Order
        %th Order Detail
        %th Date
        %th{ :colspan => 2 } Quantity / Product
        %th Account
        %th Problem
    %tbody
      - @order_details.each do |od|
        - product_name = order_detail_description(od)
        %tr{:class => needs_reconcile_warning?(od) ? 'reconcile-warning' : ''}
          %td.centered= link_to od.order_id, facility_order_path(current_facility, od.order)
          %td.centered= link_to od.id, manage_order_detail_path(od), :class => 'manage-order-detail'

          %td=h human_datetime(od.order.ordered_at)
          %td.centered=h od.quantity
          %td= product_name
          %td=h od.account
          - if od.reservation.try(:requires_but_missing_actuals?)
            %td.centered= "Actual Usage Missing #{link_to 'Enter', manage_order_detail_path(od), :class => 'manage-order-detail'}".html_safe
          - else
            %td.centered= "Price Policy Missing #{link_to 'Assign', manage_order_detail_path(od), :class => 'manage-order-detail'}".html_safe
  = will_paginate(@order_details)
  = render :partial => 'shared/reconcile_footnote'