config/routes.rb
Nucore::Application.routes.draw do
  match '/users/sign_in.pdf' => redirect('/users/sign_in')
  devise_for :users, :skip => :passwords

  if SettingsHelper.feature_on?(:password_update)
    match '/users/password/edit_current', :to => 'user_password#edit_current', :as => 'edit_current_password'
    match '/users/password/reset',        :to => 'user_password#reset',        :as => 'reset_password'
    match '/users/password/edit',         :to => 'user_password#edit',         :as => 'edit_password'
    match '/users/password/update',       :to => 'user_password#update',       :as => 'update_password'
  end

  # root route
  root :to => 'public#index'

  # authentication
  match 'switch_back',   :to => 'public#switch_back'

  # shared searches
  post  '/user_search_results', :to => 'search#user_search_results'
  match '/facilities/:facility_id/price_group/:price_group_id/account_price_group_members/search_results', :to => 'account_price_group_members#search_results'
  match '/facilities/:facility_id/accounts/user/:user_id', :to => 'facility_accounts#user_accounts', :as => 'user_accounts'

  post  'order_search' => 'order_search#index', :as => 'order_search'

  # front-end accounts
  resources :accounts, :only => [:index, :show] do
    member do
      get 'user_search'
      get 'transactions'
      get 'transactions_in_review'
    end

    if SettingsHelper.feature_on? :suspend_accounts
      match 'suspend', :to => 'accounts#suspend', :as => 'suspend'
      match 'unsuspend', :to => 'accounts#unsuspend', :as => 'unsuspend'
    end

    resources :account_users, :only => [:new, :destroy, :create, :index] do
      collection do
        get 'user_search'
      end
    end

    resources :statements, :only => [:index]

    resources :facilities, :only => [] do
      resources :statements, :only => [:show]
    end
  end

  # transaction searches
  match '/transactions', :to => 'transaction_history#my_history', :as => 'transaction_history'

  # global settings
  resources :affiliates, :except => :show

  resources :facilities, :except => [:delete] do
    collection do
      get 'list'
    end

    member do
      get 'manage'
    end

    resources :products, :only => [:index] do
      resources :product_accessories, :only => [:index, :create, :destroy], :path => 'accessories'
    end

    match 'instrument_statuses', :to => 'instruments#instrument_statuses', :as => 'instrument_statuses'

    resources :instruments do
      member do
        get 'manage'
      end

      match 'public_schedule', :to => 'instruments#public_schedule'
      match 'schedule',        :to => 'instruments#schedule'
      match 'agenda',          :to => 'instruments#agenda'
      match 'status',          :to => 'instruments#instrument_status'
      match 'switch',          :to => 'instruments#switch'

      resources :schedule_rules, :except => [:show]
      resources :product_access_groups
      resources :price_policies, :controller => 'instrument_price_policies', :except => [:show]
      resources :reservations, :only => [:new, :create, :destroy], :controller => 'facility_reservations' do
        get 'edit_admin',   :to => 'facility_reservations#edit_admin'
        put 'update_admin', :to => 'facility_reservations#update_admin'
      end

      resources :reservations, :only => [:index]
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to => 'product_users#user_search_results'
      match 'update_restrictions',        :to => 'product_users#update_restrictions'
    end

    resources :services do
      member do
        get 'manage'
      end
      resources :price_policies, :controller => 'service_price_policies', :except => [:show]
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to =>'product_users#user_search_results'
    end

    resources :items do
      member do
        get 'manage'
      end
      resources :price_policies, :controller => 'item_price_policies', :except => [:show]
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to =>'product_users#user_search_results'
    end

    resources :bundles do
      member do
        get 'manage'
      end
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to =>'product_users#user_search_results'
      resources :bundle_products, :controller => 'bundle_products', :except => [:show]
    end

    resources :price_group_products, :only => [:edit, :update]

    match 'schedule', :to => 'facilities#schedule'
    match 'agenda',   :to => 'facilities#agenda'
    resources :order_statuses, :except => [:show]

    resources :facility_users, :controller => 'facility_users', :only => [:index, :destroy] do
      collection do
        get 'search'
      end
      match 'map_user', :to => 'facility_users#map_user'
    end

    ### Feature Toggle Create Users ###
    if SettingsHelper.feature_on?(:create_users)
      resources :users, :except => [:edit, :update] do
        collection do
          get 'new_external'
          post 'search'
        end
        get   'switch_to',    :to => 'users#switch_to'
        match 'orders',       :to => 'users#orders'
        match 'reservations', :to => 'users#reservations'
        match 'accounts',     :to => 'users#accounts'
        match 'instruments',  :to => 'users#instruments'
      end
    else
      resources :users, :except => [:edit, :update, :new, :create], :constraints => {:id => /\d+/} do
        get   'switch_to',    :to => 'users#switch_to'
        match 'orders',       :to => 'users#orders'
        match 'reservations', :to => 'users#reservations'
        match 'accounts',     :to => 'users#accounts'
        match 'instruments',  :to => 'users#instruments'
      end
    end
    ######

    resources :facility_accounts, :controller => 'facility_facility_accounts', :only => [:index, :new, :create, :edit, :update] if SettingsHelper.feature_on? :recharge_accounts

    resources :orders, :controller => 'facility_orders', :only => [:index, :edit, :update, :show] do
      member do
        post 'send_receipt'
      end

      collection do
        post 'batch_update'
        get 'show_problems'
        get 'disputed'
        get 'tab_counts'
      end

      resources :order_details, :controller => 'facility_order_details', :only => [:edit, :update, :destroy] do
        member do
          get 'remove_from_journal'
        end
        get 'new_price', :to => 'facility_order_details#new_price'
        put 'resolve_dispute', :to => 'facility_order_details#resolve_dispute'
        resources :reservations, :controller => 'facility_reservations', :only => [:edit, :update, :show]
        get 'manage', :to => 'order_management/order_details#edit', :on => :member
        put 'manage', :to => 'order_management/order_details#update', :on => :member
        get 'pricing', :to => 'order_management/order_details#pricing', :on => :member
        get 'files', :to => 'order_management/order_details#files', :on => :member
      end
    end

    resources :order_imports, :only => [ :new, :create ]

    resources :reservations, :controller => 'facility_reservations', :only => :index do
      collection do
        post 'batch_update'
        get 'show_problems'
        get 'disputed'
        get 'timeline'
        get 'tab_counts'
      end
    end

    get 'accounts_receivable', :to => 'facility_accounts#accounts_receivable'

    ### Feature Toggle Editing Accounts ###
    if SettingsHelper.feature_on?(:edit_accounts)
      resources :accounts, :controller => 'facility_accounts', :only => [:new, :create, :edit, :update] do
        collection do
          get 'new_account_user_search'
          get 'user_search'
        end
        resources :account_users, :controller => 'facility_account_users', :only => [:new, :destroy, :create, :update] do
          collection do
            get 'user_search'
          end
        end
      end
    end

    resources :accounts, :controller => 'facility_accounts', :only => [:index, :show] do
      collection do
        get 'search'
        match 'search_results', :via => [:get, :post]
      end
      get '/members',                          :to => 'facility_accounts#members',        :as => 'members'
      get '/statements/:statement_id(.:format)', :to => 'facility_accounts#show_statement', :as => 'statement', :defaults => { :format => 'html' } if AccountManager.using_statements?

      if SettingsHelper.feature_on?(:suspend_accounts)
        match 'suspend',   :to => 'facility_accounts#suspend',   :as => 'suspend'
        match 'unsuspend', :to => 'facility_accounts#unsuspend', :as => 'unsuspend'
      end
    end

    ######

    resources :journals, :controller => 'facility_journals', :only => [:index, :new, :create, :update, :show] do
      post 'reconcile', :to => 'facility_journals#reconcile'
    end

    get 'bulk_email', :to => 'bulk_email#search'

    resources :price_groups do
      member do
        get 'users'
        get 'accounts'
      end

      resources :user_price_group_members, :only => [:new, :destroy, :create]

      resources :account_price_group_members, :only => [:new, :destroy, :create]
    end

    get 'notifications',       :to => 'facility_notifications#index'
    post 'notifications/send', :to => 'facility_notifications#send_notifications', :as => 'send_notifications'
    get 'transactions',        :to => 'facilities#transactions'
    get 'in_review',           :to => 'facility_notifications#in_review',          :as => 'notifications_in_review'
    post 'in_review/mark',     :to => 'facility_notifications#mark_as_reviewed',   :as => 'notifications_mark_as_reviewed'

    resources :statements, :controller => 'facility_statements', :only => [:index, :new, :show] do

app/controllers/instruments_controller.rb
class InstrumentsController < ProductsCommonController
  customer_tab  :show, :public_schedule
  admin_tab     :create, :edit, :index, :manage, :new, :schedule, :update

  # public_schedule does not require login
  skip_before_filter :authenticate_user!, :only => [:public_schedule]
  skip_authorize_resource :only => [:public_schedule]

  skip_before_filter :init_product, :only => [:instrument_statuses]

  # GET /instruments
  def index
    super
    # find current and next upcoming reservations for each instrument
    @reservations = {}
    @instruments.each { |i| @reservations[i.id] = i.reservations.upcoming[0..2]}
  end

  # GET /instruments/1
  def show
    assert_product_is_accessible!
    add_to_cart = true
    login_required = false

    # do the product have active price policies && schedule rules
    unless @instrument.available_for_purchase?
      add_to_cart = false
      flash[:notice] = t_model_error(Instrument, 'not_available', :instrument => @instrument)
    end

    # is user logged in?
    if add_to_cart && acting_user.nil?
      login_required = true
      add_to_cart = false
    end

    # is the user approved? or is the logged in user an operator of the facility (logged in user can override restrictions)
    if add_to_cart && !@instrument.is_approved_for?(acting_user)
      add_to_cart = false unless session_user and session_user.can_override_restrictions?(@instrument)
      flash[:notice] = t_model_error(Instrument, 'requires_approval_html', :instrument => @instrument, :facility => @instrument.facility, :email => @instrument.email).html_safe
    end

    # does the user have a valid payment source for purchasing this reservation?
    if add_to_cart && acting_user.accounts_for_product(@instrument).blank?
      add_to_cart=false
      flash[:notice]=t_model_error @instrument.class, 'no_accounts'
    end

    # does the product have any price policies for any of the groups the user is a member of?
    if add_to_cart && !(@instrument.can_purchase?((acting_user.price_groups + acting_user.account_price_groups).flatten.uniq.collect{ |pg| pg.id }))
      add_to_cart = false
      flash[:notice] = "You are not in a price group that may reserve instrument #{@instrument.to_s}; please contact the facility."
    end

    # when ordering on behalf of, does the staff have permissions for this facility?
    if add_to_cart && acting_as? && !session_user.operator_of?(@instrument.facility)
      add_to_cart = false
      flash[:notice] = 'You are not authorized to order instruments from this facility on behalf of a user.'
    end
    @add_to_cart = add_to_cart

    if login_required
      session[:requested_params]=request.fullpath
      return redirect_to new_user_session_path
    elsif !add_to_cart
      return redirect_to facility_path(current_facility)
    end

    redirect_to add_order_path(acting_user.cart(session_user), :order => {:order_details => [{:product_id => @instrument.id, :quantity => 1}]})
  end

  # PUT /instruments/1
  def update
    @header_prefix = "Edit"

    if @instrument.update_attributes(params[:instrument])
      flash[:notice] = 'Instrument was successfully updated.'
      return redirect_to(manage_facility_instrument_path(current_facility, @instrument))
    end

    render :action => "edit"
  end

  # GET /instruments/1/schedule
  def schedule
    @admin_reservations = @instrument.schedule.reservations.find(:all, :conditions => ['reserve_end_at > ? AND order_detail_id IS NULL', Time.zone.now])
  end

  def public_schedule
    render :layout => 'application'
  end

  # GET /facilities/:facility_id/instruments/:instrument_id/status
  def instrument_status
    begin
      @relay  = @instrument.relay
      status = Rails.env.test? ? true : @relay.get_status
      @status = @instrument.instrument_statuses.create!(:is_on => status)
    rescue Exception => e
      logger.error e
      raise ActiveRecord::RecordNotFound
    end
    respond_to do |format|
      format.html  { render :layout => false }
      format.json  { render :json => @status }
    end
  end

  def instrument_statuses
    @instrument_statuses = []
    current_facility.instruments.order(:id).includes(:relay).each do |instrument|
      # skip instruments with no relay
      next unless instrument.relay

      # skip instruments with dummy relay
      # next if instrument.relay.is_a? RelayDummy

      begin
        status = instrument.relay.get_status
        instrument_status = instrument.current_instrument_status
        # if the status hasn't changed, don't create a new status
        if instrument_status && status == instrument_status.is_on?
          @instrument_statuses << instrument_status
        else
          # || false will ensure that the value of is_on is not nil (causes a DB error)
          @instrument_statuses << instrument.instrument_statuses.create!(:is_on => status || NUCore::Database.boolean(false))
        end
      rescue Exception => e
        logger.error e.message
        @instrument_statuses << InstrumentStatus.new(:instrument => instrument, :error_message => e.message)
      end
    end
    render :json => @instrument_statuses
  end

  # GET /facilities/:facility_id/instruments/:instrument_id/switch
  def switch
    raise ActiveRecord::RecordNotFound unless params[:switch] && (params[:switch] == 'on' || params[:switch] == 'off')

    begin
      relay = @instrument.relay
      status=true

      unless Rails.env.test?
        port=@instrument.relay.port
        status = (params[:switch] == 'on' ? relay.activate : relay.deactivate)
      end

      @status = @instrument.instrument_statuses.create!(:is_on => status)
    rescue Exception => e
      logger.error "ERROR: #{e.message}"
      @status = InstrumentStatus.new(:instrument => @instrument, :error_message => e.message)
      #raise ActiveRecord::RecordNotFound
    end
    respond_to do |format|
      format.html { render :action => :instrument_status, :layout => false }
      format.json { render :json => @status }
    end
  end
end

app/helpers/price_policies_helper.rb
module PricePoliciesHelper


  def format_date(date)
    return date.is_a?(String) ? date : date.strftime("%m/%d/%Y")
  end

  def new_price_policy_path(product)
    send(:"new_facility_#{product.class.name.downcase}_price_policy_path")
  end

  def edit_price_policy_path(price_policy, url_date)
    product = price_policy.product
    send :"edit_facility_#{product.class.name.downcase}_price_policy_path", current_facility, product, url_date
  end

  def price_policy_path(price_policy_or_product, url_date)
    product = price_policy_or_product.respond_to?(:product) ? price_policy_or_product.product : price_policy_or_product
    send :"facility_#{product.class.name.downcase}_price_policy_path", current_facility, product, url_date
  end

  def price_policies_path
    send :"facility_#{@product.class.name.downcase}_price_policies_path"
  end

end

app/views/price_policies/instrument/_external_row.html.haml
%td
  Rate
  %br
  = text_field_tag "price_policy_#{pg.id}[usage_rate]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:usage_rate] : number_to_currency(pp.usage_rate, :unit => ''), :size => 8
  %br
%td
  Rate
  %br
  = text_field_tag "price_policy_#{pg.id}[reservation_rate]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:reservation_rate] : number_to_currency(pp.reservation_rate, :unit => ''), :size => 8
%td
  Rate
  %br
  = text_field_tag "price_policy_#{pg.id}[overage_rate]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:overage_rate] : number_to_currency(pp.overage_rate, :unit => ''), :size => 8
%td
  Amount
  %br
  = text_field_tag "price_policy_#{pg.id}[minimum_cost]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:minimum_cost] : number_to_currency(pp.minimum_cost, :unit => ''), :size => 8

%td
  Amount
  %br
  = text_field_tag "price_policy_#{pg.id}[cancellation_cost]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:cancellation_cost] : number_to_currency(pp.cancellation_cost, :unit => ''), :size => 8

app/views/price_policies/instrument/_internal_row.html.haml
%td
  = hidden_field_tag "price_policy_#{pg.id}[usage_rate]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:usage_rate] : number_to_currency(pp.usage_rate, :unit => ''), :class => "usage_cost"
  Adjustment
  %br
  = text_field_tag "price_policy_#{pg.id}[usage_subsidy]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:usage_subsidy] : number_to_currency(pp.usage_subsidy, :unit => ''), :size => 8
%td
  = hidden_field_tag "price_policy_#{pg.id}[reservation_rate]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:reservation_rate] : number_to_currency(pp.reservation_rate, :unit => ''), :class => "reservation_cost"
  Adjustment
  %br
  = text_field_tag "price_policy_#{pg.id}[reservation_subsidy]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:reservation_subsidy] : number_to_currency(pp.reservation_subsidy, :unit => ''), :size => 8
%td
  = hidden_field_tag "price_policy_#{pg.id}[overage_rate]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:overage_rate] : number_to_currency(pp.overage_rate, :unit => ''), :class => "overage_cost"
  Adjustment
  %br
  = text_field_tag "price_policy_#{pg.id}[overage_subsidy]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:overage_subsidy] : number_to_currency(pp.overage_subsidy, :unit => ''), :size => 8
%td
  Amount
  %br
  %span.minimum_cost
  = hidden_field_tag "price_policy_#{pg.id}[minimum_cost]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:minimum_cost] : number_to_currency(pp.minimum_cost, :unit => ''), :size => 8, :class => 'minimum_cost'
%td
  Amount
  %br
  %span.cancellation_cost
  = hidden_field_tag "price_policy_#{pg.id}[cancellation_cost]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:cancellation_cost] : number_to_currency(pp.cancellation_cost, :unit => ''), :size => 8, :class => 'cancellation_cost'

app/views/price_policies/instrument/_master_internal_row.html.haml
%td
  Rate
  %br
  = text_field_tag "price_policy_#{pg.id}[usage_rate]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:usage_rate] : number_to_currency(pp.usage_rate, :unit => ''), :size => 8, :class => 'master_usage_cost'
%td
  Rate
  %br
  = text_field_tag "price_policy_#{pg.id}[reservation_rate]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:reservation_rate] : number_to_currency(pp.reservation_rate, :unit => ''), :size => 8, :class => 'master_reservation_cost'
%td
  Rate
  %br
  = text_field_tag "price_policy_#{pg.id}[overage_rate]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:overage_rate] : number_to_currency(pp.overage_rate, :unit => ''), :size => 8, :class => 'master_overage_cost'
%td
  Amount
  %br
  = text_field_tag "price_policy_#{pg.id}[minimum_cost]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:minimum_cost] : number_to_currency(pp.minimum_cost, :unit => ''), :size => 8, :class => 'master_minimum_cost'
%td
  Amount
  %br
  = text_field_tag "price_policy_#{pg.id}[cancellation_cost]", params["price_policy_#{pg.id}"] ? params["price_policy_#{pg.id}"][:cancellation_cost] : number_to_currency(pp.cancellation_cost, :unit => ''), :size => 8, :class => 'master_cancellation_cost'

app/views/price_policies/instrument/_price_policy_fields.html.haml
= content_for :head_content do
  = javascript_include_tag 'price_policy'

= render :partial => 'price_policies/dates', :locals => { :f => f }
= f.input :interval, :label => 'Calculate Rates per', :hint => "Usage, reservation, and overage time will be rounded up based on this selection.", :collection => InstrumentPricePolicy.intervals.map{|d| [ pluralize(d, 'minute'), d ]}, :selected => @price_policies.first.usage_mins


%table.table.table-striped.table-hover.price-policy-table
  %thead
    %tr
      %th{:rowspan => 2} Price Group
      %th{:rowspan => 2} Type
      %th{:rowspan => 2} Can purchase?
      %th.super-th{:colspan => 3}
        Rates per
        %span.interval_replace
      %th{:rowspan => 2} Minimum Cost
      %th{:rowspan => 2} Reservation Cost
    %tr
      %th Actual
      %th Scheduled
      %th Overage
  %tbody
    - @price_policies.each do |pp|
      - pg = pp.price_group
      %tr
        %td= pg.name
        %td= pg.type_string
        %td= check_box_tag "price_policy_#{pg.id}[can_purchase]", '1', pp.can_purchase?, :class => 'can_purchase'
        - if !pg.is_internal?
          = render :partial => 'price_policies/instrument/external_row', :locals => { :pg => pg, :pp => pp }
        - elsif pg.is_master_internal?
          = render :partial => 'price_policies/instrument/master_internal_row', :locals => { :pg => pg, :pp => pp }
        - else
          = render :partial => 'price_policies/instrument/internal_row', :locals => { :pg => pg, :pp => pp }

app/views/price_policies/instrument/_table.html.haml
%table.table
  %thead
    %tr
      %th.actions{:rowspan => 2}
      %th{:rowspan => 2} Price Group (Type)
      %th.super-th{:colspan => 3} Rate per #{price_policies.first.usage_mins} minute#{price_policies.first.usage_mins == 1 ? '' : 's'}
      %th.currency{:rowspan => 2} Minimum Cost
      %th.currency{:rowspan => 2} Reservation Cost
    %tr
      %th.currency Actual
      %th.currency Scheduled
      %th.currency Overage
  %tbody
    - price_policies_to_show = price_policies.select { |pp| pp.can_purchase? }
    - price_policies_to_show.each do |price_policy|
      %tr
        - if price_policies_to_show.first == price_policy
          %td.centered{ :rowspan => price_policies_to_show.length }
            - unless price_policies.all?{|pp| pp.editable?} and can? :edit, PricePolicy
              %p.muted Edit
              %p.muted Remove
            - else
              %p= link_to('Edit', edit_facility_instrument_price_policy_path(current_facility, @product, url_date))
              %p= link_to('Remove', facility_instrument_price_policy_path(current_facility, @product, url_date), :confirm => 'Are you sure?', :method => :delete)
        %td= "#{price_policy.price_group.name} (#{price_policy.price_group.type_string})"
        - if price_policy.valid?
          %td.currency= human_rate_calculation(price_policy.usage_rate, price_policy.usage_subsidy)
          %td.currency= human_rate_calculation(price_policy.reservation_rate, price_policy.reservation_subsidy)
          %td.currency= human_rate_calculation(price_policy.overage_rate, price_policy.overage_subsidy)
          %td.currency= number_to_currency price_policy.minimum_cost
          %td.currency= number_to_currency price_policy.cancellation_cost
        - else
          %td.centered{:colspan => 5}
            = t('price_policies.problem')
            = price_policy.errors.full_messages.to_sentence