config/routes.rb
Nucore::Application.routes.draw do
  match '/users/sign_in.pdf' => redirect('/users/sign_in')
  devise_for :users, :skip => :passwords

  if SettingsHelper.feature_on?(:password_update)
    match '/users/password/edit_current', :to => 'user_password#edit_current', :as => 'edit_current_password'
    match '/users/password/reset',        :to => 'user_password#reset',        :as => 'reset_password'
    match '/users/password/edit',         :to => 'user_password#edit',         :as => 'edit_password'
    match '/users/password/update',       :to => 'user_password#update',       :as => 'update_password'
  end

  # root route
  root :to => 'public#index'

  # authentication
  match 'switch_back',   :to => 'public#switch_back'

  # shared searches
  post  '/user_search_results', :to => 'search#user_search_results'
  match '/facilities/:facility_id/price_group/:price_group_id/account_price_group_members/search_results', :to => 'account_price_group_members#search_results'
  match '/facilities/:facility_id/accounts/user/:user_id', :to => 'facility_accounts#user_accounts', :as => 'user_accounts'

  post  'order_search' => 'order_search#index', :as => 'order_search'

  # front-end accounts
  resources :accounts, :only => [:index, :show] do
    member do
      get 'user_search'
      get 'transactions'
      get 'transactions_in_review'
    end

    if SettingsHelper.feature_on? :suspend_accounts
      match 'suspend', :to => 'accounts#suspend', :as => 'suspend'
      match 'unsuspend', :to => 'accounts#unsuspend', :as => 'unsuspend'
    end

    resources :account_users, :only => [:new, :destroy, :create, :index] do
      collection do
        get 'user_search'
      end
    end

    resources :statements, :only => [:index]

    resources :facilities, :only => [] do
      resources :statements, :only => [:show]
    end
  end

  # transaction searches
  match '/transactions', :to => 'transaction_history#my_history', :as => 'transaction_history'

  # global settings
  resources :affiliates, :except => :show

  resources :facilities, :except => [:delete] do
    collection do
      get 'list'
    end

    member do
      get 'manage'
    end

    resources :products, :only => [:index] do
      resources :product_accessories, :only => [:index, :create, :destroy], :path => 'accessories'
    end

    match 'instrument_statuses', :to => 'instruments#instrument_statuses', :as => 'instrument_statuses'

    resources :instruments do
      member do
        get 'manage'
      end

      match 'public_schedule', :to => 'instruments#public_schedule'
      match 'schedule',        :to => 'instruments#schedule'
      match 'agenda',          :to => 'instruments#agenda'
      match 'status',          :to => 'instruments#instrument_status'
      match 'switch',          :to => 'instruments#switch'

      resources :schedule_rules, :except => [:show]
      resources :product_access_groups
      resources :price_policies, :controller => 'instrument_price_policies', :except => [:show]
      resources :reservations, :only => [:new, :create, :destroy], :controller => 'facility_reservations' do
        get 'edit_admin',   :to => 'facility_reservations#edit_admin'
        put 'update_admin', :to => 'facility_reservations#update_admin'
      end

      resources :reservations, :only => [:index]
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to => 'product_users#user_search_results'
      match 'update_restrictions',        :to => 'product_users#update_restrictions'
    end

    resources :services do
      member do
        get 'manage'
      end
      resources :price_policies, :controller => 'service_price_policies', :except => [:show]
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to =>'product_users#user_search_results'
    end

    resources :items do
      member do
        get 'manage'
      end
      resources :price_policies, :controller => 'item_price_policies', :except => [:show]
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to =>'product_users#user_search_results'
    end

    resources :bundles do
      member do
        get 'manage'
      end
      resources :users, :controller => 'product_users', :except => [:show, :edit, :create]
      match '/users/user_search_results', :to =>'product_users#user_search_results'
      resources :bundle_products, :controller => 'bundle_products', :except => [:show]
    end

    resources :price_group_products, :only => [:edit, :update]

    match 'schedule', :to => 'facilities#schedule'
    match 'agenda',   :to => 'facilities#agenda'
    resources :order_statuses, :except => [:show]

    resources :facility_users, :controller => 'facility_users', :only => [:index, :destroy] do
      collection do
        get 'search'
      end
      match 'map_user', :to => 'facility_users#map_user'
    end

    ### Feature Toggle Create Users ###
    if SettingsHelper.feature_on?(:create_users)
      resources :users, :except => [:edit, :update] do
        collection do
          get 'new_external'
          post 'search'
        end
        get   'switch_to',    :to => 'users#switch_to'
        match 'orders',       :to => 'users#orders'
        match 'reservations', :to => 'users#reservations'
        match 'accounts',     :to => 'users#accounts'
        match 'instruments',  :to => 'users#instruments'
      end
    else
      resources :users, :except => [:edit, :update, :new, :create], :constraints => {:id => /\d+/} do
        get   'switch_to',    :to => 'users#switch_to'
        match 'orders',       :to => 'users#orders'
        match 'reservations', :to => 'users#reservations'
        match 'accounts',     :to => 'users#accounts'
        match 'instruments',  :to => 'users#instruments'
      end
    end
    ######

    resources :facility_accounts, :controller => 'facility_facility_accounts', :only => [:index, :new, :create, :edit, :update] if SettingsHelper.feature_on? :recharge_accounts

    resources :orders, :controller => 'facility_orders', :only => [:index, :edit, :update, :show] do
      member do
        post 'send_receipt'
      end

      collection do
        post 'batch_update'
        get 'show_problems'
        get 'disputed'
        get 'tab_counts'
      end

      resources :order_details, :controller => 'facility_order_details', :only => [:edit, :update, :destroy] do
        member do
          get 'remove_from_journal'
        end
        get 'new_price', :to => 'facility_order_details#new_price'
        put 'resolve_dispute', :to => 'facility_order_details#resolve_dispute'
        resources :reservations, :controller => 'facility_reservations', :only => [:edit, :update, :show]
        get 'manage', :to => 'order_management/order_details#edit', :on => :member
        put 'manage', :to => 'order_management/order_details#update', :on => :member
        get 'pricing', :to => 'order_management/order_details#pricing', :on => :member
        get 'files', :to => 'order_management/order_details#files', :on => :member
      end
    end

    resources :order_imports, :only => [ :new, :create ]

    resources :reservations, :controller => 'facility_reservations', :only => :index do
      collection do
        post 'batch_update'
        get 'show_problems'
        get 'disputed'
        get 'timeline'
        get 'tab_counts'
      end
    end

    get 'accounts_receivable', :to => 'facility_accounts#accounts_receivable'

    ### Feature Toggle Editing Accounts ###
    if SettingsHelper.feature_on?(:edit_accounts)
      resources :accounts, :controller => 'facility_accounts', :only => [:new, :create, :edit, :update] do
        collection do
          get 'new_account_user_search'
          get 'user_search'
        end
        resources :account_users, :controller => 'facility_account_users', :only => [:new, :destroy, :create, :update] do
          collection do
            get 'user_search'
          end
        end
      end
    end

    resources :accounts, :controller => 'facility_accounts', :only => [:index, :show] do
      collection do
        get 'search'
        match 'search_results', :via => [:get, :post]
      end
      get '/members',                          :to => 'facility_accounts#members',        :as => 'members'
      get '/statements/:statement_id(.:format)', :to => 'facility_accounts#show_statement', :as => 'statement', :defaults => { :format => 'html' } if AccountManager.using_statements?

      if SettingsHelper.feature_on?(:suspend_accounts)
        match 'suspend',   :to => 'facility_accounts#suspend',   :as => 'suspend'
        match 'unsuspend', :to => 'facility_accounts#unsuspend', :as => 'unsuspend'
      end
    end

    ######

    resources :journals, :controller => 'facility_journals', :only => [:index, :new, :create, :update, :show] do
      post 'reconcile', :to => 'facility_journals#reconcile'
    end

    get 'bulk_email', :to => 'bulk_email#search'

    resources :price_groups do
      member do
        get 'users'
        get 'accounts'
      end

      resources :user_price_group_members, :only => [:new, :destroy, :create]

      resources :account_price_group_members, :only => [:new, :destroy, :create]
    end

    get 'notifications',       :to => 'facility_notifications#index'
    post 'notifications/send', :to => 'facility_notifications#send_notifications', :as => 'send_notifications'
    get 'transactions',        :to => 'facilities#transactions'
    get 'in_review',           :to => 'facility_notifications#in_review',          :as => 'notifications_in_review'
    post 'in_review/mark',     :to => 'facility_notifications#mark_as_reviewed',   :as => 'notifications_mark_as_reviewed'

    resources :statements, :controller => 'facility_statements', :only => [:index, :new, :show] do

app/controllers/facility_order_details_controller.rb
class FacilityOrderDetailsController < ApplicationController
  admin_tab     :all
  before_filter :authenticate_user!
  before_filter :check_acting_as
  before_filter :init_current_facility
  before_filter :init_order_detail, :except => :remove_from_journal

  load_and_authorize_resource :class => OrderDetail

  include FacilityOrderStatusHelper
  helper_method :new_or_in_process_orders, :problem_orders, :disputed_orders

  def initialize
    @active_tab = 'admin_orders'
    super
  end

  # GET /facilities/:facility_id/orders/:order_id/order_details/:id/edit
  def edit
    set_active_tab
    @in_open_journal=@order_detail.journal && @order_detail.journal.open?

    condition=case @order_detail.account
      when NufsAccount
        (@order_detail.journal && @order_detail.journal.is_successful) || OrderDetail.need_journal.include?(@order_detail)
      else
        !@order_detail.statement.nil?
    end

    @can_be_reconciled=condition && @order_detail.complete? && !@order_detail.in_dispute?

    if @in_open_journal
      flash.now[:notice]=I18n.t 'controllers.facility_order_details.edit.notice.open_journal'
    elsif @order_detail.order_status.name == 'Complete'
      if @order_detail.reservation.try(:requires_but_missing_actuals?)
        flash.now[:notice]=I18n.t 'controllers.facility_order_details.edit.notice.no_actuals'
      elsif @order_detail.price_policy.nil?
        flash.now[:notice]=I18n.t 'controllers.facility_order_details.edit.notice.no_policy'
      end
    end

  end

  # PUT /facilities/:facility_id/orders/:order_id/order_details/:id
  def update
    unless @order_detail.state == 'new' || @order_detail.state == 'inprocess' || can?(:update, @order_detail)
      raise ActiveRecord::RecordNotFound
    end

    @order_detail.transaction do
      begin
        # process account change
        process_account_change

        od_params=params[:order_detail]

        # process all changes except order status
        @order_detail.attributes = od_params.reject{|k, v| k == :order_status_id}
        @order_detail.actual_cost = od_params[:actual_cost].gsub(/[^\d\.]/,'') if od_params[:actual_cost]
        @order_detail.actual_subsidy = od_params[:actual_subsidy].gsub(/[^\d\.]/,'') if od_params[:actual_subsidy]
        @order_detail.updated_by = session_user.id
        @order_detail.reconciled_note=od_params[:reconciled_note] if od_params[:reconciled_note]

        if params[:assign_price_policy]
          @order_detail.assign_price_policy
        elsif @order_detail.price_policy.nil?
          @order_detail.assign_estimated_price
        end

        @order_detail.save!

        # process order status change
        if od_params[:order_status_id]
          os = OrderStatus.find(od_params[:order_status_id])
          # cancel instrument orders
          if os.root == OrderStatus.cancelled.first && @order_detail.reservation
            raise "Order # #{@order_detail} failed cancellation." unless @order_detail.cancel_reservation(session_user, os, true, params[:with_cancel_fee] == '1')
          # cancel other orders or change status of any order
          else
            @order_detail.change_status!(os)
          end
        end
        @order_detail.save!
        flash[:notice] = 'The order has been updated successfully'
        redirect_to(params[:return_to].present? ? params[:return_to] :
                    @order_detail.reservation ? timeline_facility_reservations_path(current_facility) :
                    facility_orders_path(current_facility)) and return
      rescue Exception => e
        flash.now[:error] = 'An error was encounted while updating the order'
        Rails.logger.warn "#{e.message}\n#{e.backtrace.join("\n")}"
        raise ActiveRecord::Rollback
      end
    end
    render :action => 'edit'
  end

  # POST /facilities/:facility_id/orders/:order_id/order_details/:order_detail_id/resolve_dispute
  def resolve_dispute
    unless current_user.manager_of?(current_facility) && @order_detail.dispute_at && @order_detail.dispute_resolved_at.nil?
      raise ActiveRecord::RecordNotFound
    end

    @order_detail.transaction do
      begin
        # process account change
        process_account_change

        # update order detail
        @order_detail.attributes          = params[:order_detail]
        @order_detail.updated_by          = session_user.id
        @order_detail.dispute_resolved_at = Time.zone.now
        @order_detail.reviewed_at         = Time.zone.now
        @order_detail.save!

        flash[:notice] = 'The dispute has been resolved successfully'
        redirect_to (@order_detail.reservation ? disputed_facility_reservations_path : disputed_facility_orders_path) and return
      rescue Exception => e
        flash.now[:error] = "An error was encountered while resolving the dispute"
        raise ActiveRecord::Rollback
      end
    end
    @order_detail.dispute_resolved_at = nil #rollback does not reset the un-saved value, so have to manually set to the view will render correctly
    render :action => 'edit'
  end


  # GET /facilities/:facility_id/orders/:order_id/order_details/:order_detail_id/new_price
  def new_price
    qty           = params[:quantity].to_i

    cost    = qty * @order_detail.price_policy.unit_cost
    subsidy = qty * @order_detail.price_policy.unit_subsidy
    total   = cost - subsidy

    render :json => [cost, subsidy, total]
  end


  def remove_from_journal
    oid=params[:id]
    return redirect_to :back if oid.blank?

    od=OrderDetail.find(oid.to_i)

    OrderDetail.transaction do
      jr=JournalRow.where(:journal_id => od.journal_id, :order_detail_id => od.id).first
      jr.try :destroy
      od.update_attributes! :journal_id => nil
    end

    flash[:notice]=I18n.t 'controllers.facility_order_details.remove_from_journal.notice'
    redirect_to facility_order_path(current_facility, od.order)
  end


  def destroy
    if @order.to_be_merged?
      begin
        @order_detail.destroy
        flash[:notice]=I18n.t 'controllers.facility_order_details.destroy.success'
      rescue => e
        Rails.logger.error "#{e.message}:#{e.backtrace.join("\n")}"
        flash[:error]=I18n.t 'controllers.facility_order_details.destroy.error', @order_detail.to_s
      end
    else
      flash[:notice]=I18n.t 'controllers.facility_order_details.destroy.notice'
      return redirect_to facility_order_path(current_facility, @order)
    end

    redirect_to facility_order_path(current_facility, @order.merge_order)
  end


  private

  def process_account_change
    return if params[:order_detail][:account_id].to_i == @order_detail.account_id
    @order_detail.account=Account.find(params[:order_detail][:account_id])
    @order_detail.statement=nil
    @order_detail.save!
  end

  def set_active_tab
    if @order_detail.reservation
      @active_tab = "admin_reservations"
    else
      @active_tab = "admin_orders"
    end
  end

  def init_order_detail
    @order = Order.find(params[:order_id])
    raise ActiveRecord::RecordNotFound unless @order
    @order_detail = @order.order_details.find(params[:id] || params[:order_detail_id])
  end
end

app/views/facility_order_details/_price_row.html.haml
- if @order_detail.cost_estimated?
  %td.currency.estimated_cost= show_estimated_cost(@order_detail)
  %td.currency.estimated_subsidy= show_estimated_subsidy(@order_detail)
  %td.currency
    %span#actual_total= show_estimated_total(@order_detail)
- elsif @order_detail.price_policy.nil?
  %td.currency.unassigned_cost Unassigned
  %td.currency.unassigned_subsidy Unassigned
  %td.currency.unassigned_total Unassigned
- else
  - html_opts={ :size => 8 }
  - html_opts.merge!(:disabled => 'disabled') if @in_open_journal || @order_detail.reconciled?
  - actual_opts=html_opts.merge({:value => number_with_precision(@order_detail.actual_cost, :precision => 2), :id => 'actual_cost'})
  %td.currency.actual_cost= "$#{form.text_field(:actual_cost, actual_opts)}".html_safe
  - sub_opts=html_opts.merge({:value => number_with_precision(@order_detail.actual_subsidy, :precision => 2), :id => 'actual_subsidy', :disabled => !@order_detail.price_policy.has_subsidy?})
  %td.currency.actual_subsidy= "$#{form.text_field(:actual_subsidy, sub_opts)}".html_safe
  %td.currency.actual_total
    %span#actual_total= show_actual_total(@order_detail)

app/views/facility_order_details/edit.html.haml
= content_for :head_content do
  = javascript_include_tag 'uploadify/jquery.uploadify.v2.1.0.min'
  = javascript_include_tag 'uploadify/swfobject'
  :javascript
    $(document).ready(function() {
      $('#file_upload').uploadify({
        'uploader'     : '#{asset_path('uploadify/uploadify.swf')}',
        'fileDataName' : 'fileData',
        'script'       : "#{add_uploader_file_path(current_facility, @order_detail.product.parameterize, @order_detail.product.url_name)}",
        'cancelImg'    : "#{asset_path('uploadify/cancel.png')}",
        'auto'         : false,
        'method'       : 'get',
        'multi'        : true,
        'folder'       : '/uploads',
        'onAllComplete' : function () {window.location.reload();},
        'scriptData'   : {
          '_nucore_session'    : '#{u cookies['_nucore_session']}',
          'authenticity_token' : encodeURIComponent('#{u form_authenticity_token if protect_against_forgery?}'),
          'file_type'          : 'sample_result',
          'order_detail_id'    : '#{@order_detail.id}'
        }
      });

      $("#quantity").change(function () {
        if($('#actual_cost').length == 0)
          return;

        $('#submit').attr('disabled', true);
        $.getJSON(
          "#{facility_order_order_detail_new_price_path(current_facility, @order, @order_detail)}?quantity=" + this.value,
          function(data) {
            $("#actual_cost").val(new Number(data[0]).toFixed(2));
            $("#actual_subsidy").val(new Number(data[1]).toFixed(2));
            $("#actual_total").html("$" + new Number(data[2]).toFixed(2));
            $('#submit').attr('disabled', false);
          }
        );
      });

      $("input[type='text']").change(function () {
        if (this.id == 'actual_cost' || this.id == 'actual_subsidy') {
          $("#actual_total").html("$" + ($("#actual_cost")[0].value - $("#actual_subsidy")[0].value).toFixed(2));
        }
      });

      if($('#cancel-fee-opt').length > 0) {
        $('#order_detail_order_status_id').change(function() {
          if($(this).val() == #{OrderStatus.cancelled.first.id})
            $('#cancel-fee-opt').show()
          else
            $('#cancel-fee-opt').hide()
        })
      }
    });

  - if @can_be_reconciled
    :javascript
      $(function() {
        $('#reconcile-note').hide();

        $('#order_detail_order_status_id').change(function() {
          if($(this).val() == #{OrderStatus.reconciled.first.id})
            $('#reconcile-note').show();
          else
            $('#reconcile-note').hide();
        });
      });

= content_for :h1 do
  = current_facility
= content_for :tabnav do
  - if @order_detail.problem_order?
    - tab = 'problem'
  - elsif @order_detail.in_dispute?
    - tab = 'disputed'
  - elsif @order_detail.complete?
    - tab = ''
  - else
    - tab = 'new'
  = render :partial => "admin/shared/tabnav_#{@order_detail.reservation ? 'reservation' : 'order'}", :locals => { :secondary_tab => tab }

%h2= t('.head.h2', :order_number => @order_detail.to_s)
= simple_form_for(@order_detail, :url => (@order_detail.in_dispute? ? facility_order_order_detail_resolve_dispute_path(current_facility, @order, @order_detail) : facility_order_order_detail_path(current_facility, @order, @order_detail)), :html => {:method => :put}) do |f|
  = hidden_field_tag :return_to, request.referer if request.referer =~ /\/facilities\/.+\/orders\/[0-9]+\/edit/
  = f.error_messages
  %label= link_to t('.label.ordered.summary', :order_number => @order.id), facility_order_path(current_facility, @order)

  = f.input :ordered_at, :as => :readonly, :label => t('.label.ordered.at')
  = f.input :user, :as => :readonly
  = f.input :created_by_user, :as => :readonly
  = f.input :fulfilled_at, :as => :readonly if @order_detail.fulfilled_at

  %label= t('.label.account')
  - html_opts=@in_open_journal ? { :disabled => 'disabled' } : {}
  - # make sure that the account it was purchased under is available, even if it's no
  - # longer available for the owner
  - available_accounts = @order.user.account_users.active.collect{|au| au.account}
  - available_accounts << @order.account if available_accounts.index(@order.account).nil?
  = f.collection_select(:account_id, available_accounts, :id, :account_pretty, {}, html_opts)


  %label= t('.label.assigned')
  - if @order_detail.complete?
    =h @order_detail.assigned_user ? @order_detail.assigned_user.full_name : 'Unassigned'
  - else
    = f.collection_select(:assigned_user_id, User.find_users_by_facility(current_facility), :id, :full_name, :prompt => 'Unassigned')
  .grid_6.omega.margin_bottom
    - # Dispute form
    - if @order_detail.in_dispute?
      .box.margin_bottom
        %h3= t('.head.h3')
        %p= t('.instruct.dispute')
        %ul.form
          %li
            %label= t('.label.dispute.on')
            =h human_datetime(@order_detail.dispute_at)
          %li
            %label= t('.label.dispute.reason')
            =h @order_detail.dispute_reason
          %li
            %label.required= t('.label.dispute.resolve')
            = f.text_field :dispute_resolved_reason

    - # Dispute Results
    - if @order_detail.dispute_resolved_at
      .box.margin_bottom
        %h3= t('.head.h3-2')
        %ul.form
          %li
            %label= t('.label.dispute.on')
            =h human_datetime(@order_detail.dispute_at)
          %li
            %label= t('.label.dispute.reason')
            =h @order_detail.dispute_reason
          %li
            %label= t('.label.resolved')
            =h human_datetime(@order_detail.dispute_resolved_at)
          %li
            %label= t('.label.dispute.resolve')
            =h @order_detail.dispute_resolved_reason

    - # Results Files
    - if @order_detail.product.is_a?(Service)
      .box
        %h3= t('file_uploads.sample_result.title')
        - @results = @order_detail.stored_files.sample_result.sort{|a,b| a.created_at <=> b.created_at}
        - if @results.empty?
          %p= t('file_uploads.sample_result.none')
        - else
          %ul.form
            - i = 0
            - @results.each do |stored_file|
              %li
                == #{link_to("Results File #{i+=1}", stored_file.file.url)}:
                = human_datetime(stored_file.created_at)
                == - (#{link_to('Remove', remove_product_file_path(current_facility, @order_detail.product.parameterize, @order_detail.product, stored_file, :return_to => request.fullpath), :method => :delete, :confirm => 'Are you sure?')})
        %h3= t('file_uploads.sample_result.upload')
        #file_upload= t('file_uploads.widget.error_loading')
        %br
        = link_to t('file_uploads.widget.start'), "javascript:$('#file_upload').uploadifyUpload();"
        == &nbsp;&nbsp;|&nbsp;&nbsp;
        = link_to t('file_uploads.widget.clear_queue'), "javascript:$('#file_upload').uploadifyClearQueue()"
  .clear
  - # Product table
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th{:colspan => 2}= t('.th.product')
        %th Status
        %th.currency= "#{@order_detail.cost_estimated? ? 'Estimated ' : '' }Cost"
        %th.currency.subsidy_header
          = @order_detail.price_policy.price_group if @order_detail.price_policy
          = "#{@order_detail.cost_estimated? ? 'Estimated' : ''} Subsidy"

        %th.currency= "#{@order_detail.cost_estimated? ? 'Estimated ' : '' }Total"
    %tbody
      %tr
        %td.centered
          - if @order_detail.product.is_a?(Instrument)
            =h @order_detail.quantity
          - else
            - html_opts={ :id => 'quantity', :size => 3 }
            - html_opts.merge!(:disabled => 'disabled') if @in_open_journal || @order_detail.reconciled?
            = f.text_field :quantity, html_opts
        %td
          %ul
            - product_name = order_detail_description(@order_detail)
            %li= product_name
            - if @order_detail.reservation
              %li.indented= link_to(@order_detail.reservation, edit_facility_order_order_detail_reservation_path(current_facility, @order, @order_detail, @order_detail.reservation))
            - if @order_detail.survey_completed?
              %li.indented= link_to('View Order Form', @order_detail.external_service_receiver.response_data, :target => '_blank')
            - unless @order_detail.stored_files.template_result.empty?
              %li.indented= link_to('View Order File', @order_detail.stored_files.template_result.first.file.url)
        %td
          - if @can_be_reconciled
            = f.collection_select(:order_status_id, [ OrderStatus.complete.first, OrderStatus.cancelled.first, OrderStatus.reconciled.first ], :id, :name_with_level)
            - if @order_detail.account.is_a?(NufsAccount) && @order_detail.journal
              == <br/><br/>#{link_to t('.link.remove'), remove_from_journal_facility_order_order_detail_path(current_facility, @order, @order_detail)}
          - elsif @order_detail.complete?
            = f.collection_select(:order_status_id, [ OrderStatus.complete.first, OrderStatus.cancelled.first ], :id, :name_with_level)
          - elsif @order_detail.reconciled?
            =h @order_detail.order_status
          - else
            = f.collection_select(:order_status_id, OrderStatus.non_protected_statuses(current_facility), :id, :name_with_level)

          - if @order_detail.product.is_a? Instrument
            %div#cancel-fee-opt
              = label_tag 'with_cancel_fee', t('.label.with_cancel_fee')
              = check_box_tag 'with_cancel_fee'

        - if @order_detail.product.is_a?(Instrument) && @order_detail.complete?
          - res = @order_detail.reservation
          - if res && res.requires_but_missing_actuals?
            %td.centered{:colspan => '3'}= t('.notice.no_time')
          - else
            = render :partial => 'price_row', :locals => { :form => f }
        - else
          = render :partial => 'price_row', :locals => { :form => f }
      %tr
        %td{:colspan => '6'}
          %label.inline_wide Note:
          - opts={ :maxlength => 100, :size => 100 }
          - opts.merge!(:disabled => 'disabled') if @order_detail.reconciled?
          = f.text_field(:note, opts)
          - if @can_be_reconciled || @order_detail.reconciled?
            %br/
            %span#reconcile-note
              %label.inline_wide= t('.label.reconcile')
              = f.text_field(:reconciled_note, {:maxlength => 255, :size => 100})

  - if @order_detail.cost_estimated?
    %p.footnote= t('.foot.estimated')
  - elsif @order_detail.price_policy.nil?
    %p.footnote= t('.foot.price_policy')
  - else
    %p.footnote= t('.foot.default')

  - if @order_detail.in_dispute?
    %ul.inline
      %li= submit_tag 'Resolve Dispute', {:class => 'btn', :id => 'submit'}
      %li= link_to 'Cancel', disputed_facility_orders_path
  - else
    - cancel_link=request.referrer.blank? ? facility_transactions_path(current_facility) : request.referrer
    %p= t('.notice.save_html')
    %ul.inline
      - attrs={:class => 'btn', :id => 'submit'}
      - attrs.merge!(:name => 'assign_price_policy') if @order_detail.price_policy.nil? && @order_detail.order_status.name == 'Complete'
      %li= submit_tag 'Save', attrs
      %li= link_to 'Cancel', cancel_link

- if @order_detail.bundle
  -# BUNDLE TABLE
  %br
  %br
  %br
  %h3= t('.head.h3-5')
  %p= t('.instruct.bundle')
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th= t('.th.order')
        %th{:colspan => 2}= t('.th.quantity')
        %th= t('.th.status')
        %th= t('.th.assigned')
    %tbody
      - @order.order_details.find(:all, :conditions => {:group_id => @order_detail.group_id}).each do |od|
        - product_name = order_detail_description(od)
        %tr
          %td= link_to od, facility_order_path(current_facility, @order)
          %td= od.quantity
          %td= product_name
          %td=h od.order_status
          %td=h od.assigned_user.nil? ? '' : od.assigned_user.full_name